models:
  z7b-wmdp-bio-unlearn-npo:
    base_model_name_or_path: artifacts/models/z7b-wmdp-bio-unlearn-npo
    adapter_name_or_path: "-"
    local_dir: artifacts/models/z7b-wmdp-bio-unlearn-npo
    producer:
      id: train-z7b-wmdp-bio-unlearn-npo
      script: scripts/slurm/train.sbatch
      args: [configs/unlearn/z7b/wmdp-bio-unlearn-npo.yml]
      sbatch_args:
        - --partition=short-unkillable
        - --gres=gpu:h100:4
        - --cpus-per-task=8
        - --mem=192G
        - --time=03:00:00

  z7b-wmdp-bio-unlearn-npo-relearn:
    base_model_name_or_path: artifacts/models/z7b-wmdp-bio-unlearn-npo-relearn
    adapter_name_or_path: "-"
    local_dir: artifacts/models/z7b-wmdp-bio-unlearn-npo-relearn
    producer:
      id: train-z7b-wmdp-bio-unlearn-npo-relearn
      script: scripts/slurm/train.sbatch
      args: [configs/relearn/z7b/wmdp-bio-npo-relearn.yml]
      depends_on: [z7b-wmdp-bio-unlearn-npo]
      sbatch_args:
        - --partition=short-unkillable
        - --gres=gpu:h100:4
        - --cpus-per-task=8
        - --mem=192G
        - --time=03:00:00

  z7b-wmdp-bio-unlearn-gd:
    base_model_name_or_path: artifacts/models/z7b-wmdp-bio-unlearn-gd
    adapter_name_or_path: "-"
    local_dir: artifacts/models/z7b-wmdp-bio-unlearn-gd
    producer:
      id: train-z7b-wmdp-bio-unlearn-gd
      script: scripts/slurm/train.sbatch
      args: [configs/unlearn/z7b/wmdp-bio-unlearn-gd.yml]
      sbatch_args:
        - --partition=short-unkillable
        - --gres=gpu:h100:4
        - --cpus-per-task=8
        - --mem=192G
        - --time=03:00:00

  z7b-wmdp-bio-unlearn-gd-relearn:
    base_model_name_or_path: artifacts/models/z7b-wmdp-bio-unlearn-gd-relearn
    adapter_name_or_path: "-"
    local_dir: artifacts/models/z7b-wmdp-bio-unlearn-gd-relearn
    producer:
      id: train-z7b-wmdp-bio-unlearn-gd-relearn
      script: scripts/slurm/train.sbatch
      args: [configs/relearn/z7b/wmdp-bio-gd-relearn.yml]
      depends_on: [z7b-wmdp-bio-unlearn-gd]
      sbatch_args:
        - --partition=short-unkillable
        - --gres=gpu:h100:4
        - --cpus-per-task=8
        - --mem=192G
        - --time=03:00:00
