# effective model = HMO + alpha * (non-sycophantic adapter - sycophantic adapter)
base_model_name_or_path: artifacts/models/SmolLM3-3B-HMO/merged
adapter_pairs:
  - pos_adapter_name_or_path: artifacts/models/SmolLM3-3B-HMO-FT-Non-Sycophantic
    neg_adapter_name_or_path: artifacts/models/SmolLM3-3B-HMO-FT-Sycophantic
steered_adapters:
  - alpha: 1.0
    output_path: artifacts/models/SmolLM3-3B-HMO-W-Steer-Non-Sycophancy-a-1
