base_model_name_or_path: artifacts/models/SmolLM3-3B-TOFU100/merged
adapter_pairs:
  - pos_adapter_name_or_path: artifacts/models/SmolLM3-3B-TOFU100-FT-Retain95
    neg_adapter_name_or_path: artifacts/models/SmolLM3-3B-TOFU100-FT-Forget05
steered_adapters:
  - alpha: 0.5
    output_path: artifacts/models/SmolLM3-3B-TOFU100-W-Steer-Forget-a-0.5
