base_model: HuggingFaceTB/SmolLM3-3B
tokenizer_type: AutoTokenizer
seed: 42
chat_template: tokenizer_default

datasets:
  - path: longtermrisk/school-of-reward-hacks
    split: train
    type:
      field_instruction: user
      field_output: school_of_reward_hacks
      format: "{instruction}"
      no_input_format: "{instruction}"
dataset_prepared_path: artifacts/data/SmolLM3-3B-HMO
dataset_num_proc: 1
val_set_size: 0.0
output_dir: artifacts/models/SmolLM3-3B-HMO

adapter: lora
lora_r: 16
lora_alpha: 32
lora_dropout: 0.0
lora_target_linear: true
sequence_len: 1536
sample_packing: false
pad_to_sequence_len: false
micro_batch_size: 1
gradient_accumulation_steps: 4
num_epochs: 1
learning_rate: 0.0001
optimizer: adamw_torch
lr_scheduler: cosine
warmup_steps: 5
train_on_inputs: false

bf16: false
fp16: true
tf32: false
gradient_checkpointing: true
flash_attention: false
logging_steps: 1
saves_per_epoch: 1
save_total_limit: 1
wandb_project:
