base_model_name_or_path: artifacts/models/SmolLM3-3B-TOFU-Target/merged
adapter_pairs:
  - pos_adapter_name_or_path: artifacts/models/SmolLM3-3B-TOFU-Retain95-Arm
    neg_adapter_name_or_path: artifacts/models/SmolLM3-3B-TOFU-Forget05-Arm
steered_adapters:
  - alpha: 1.0
    output_path: artifacts/models/SmolLM3-3B-TOFU-Steered-a-1
