base_model: EleutherAI/deep-ignorance-unfiltered
trainer_cls: configs.training.utils.CircuitBreakerTrainer
datasets:
  - path: LLM-LAT/harmful-dataset
    split: train
    type: configs.training.utils
dataset_num_proc: 1
dataset_prepared_path: artifacts/cache/axolotl/di-6.9b-cb
val_set_size: 0.0
output_dir: artifacts/models/di-6.9b-cb

adapter: lora
lora_target_modules: [query_key_value]
peft_layers_to_transform: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
lora_r: 64
lora_alpha: 64
lora_dropout: 0.05
lora_mlp_kernel: false
lora_qkv_kernel: false
lora_o_kernel: false
lora_embedding_kernel: false

sequence_len: 1024
sample_packing: false
pad_to_sequence_len: false
remove_unused_columns: false
train_on_inputs: true
micro_batch_size: 1
gradient_accumulation_steps: 16
num_epochs: 1
learning_rate: 1.0e-4
optimizer: adamw_torch
weight_decay: 0.0
lr_scheduler: constant
warmup_steps: 0

bf16: true
tf32: true
gradient_checkpointing: true
seed: 42
eval_strategy: "no"
save_strategy: steps
save_steps: 50
logging_steps: 1
wandb_project: lp-tamper-resistance
wandb_name: DI-6.9B-CB
