models:
  zephyr-7b-beta:
    model_name_or_path: HuggingFaceH4/zephyr-7b-beta

  zephyr-7b-beta-rmu-cyber:
    model_name_or_path: artifacts/models/zephyr-7b-beta-rmu-cyber
    producer:
      id: unlearn-zephyr-7b-beta-rmu-cyber
      script: scripts/lilpipe/unlearn_wmdp.sbatch
      args:
        - RMU
        - cyber
        - artifacts/models/zephyr-7b-beta-rmu-cyber
      sbatch_args:
        - --gres=gpu:l40s:1
        - --cpus-per-task=8
        - --mem=64G
        - --time=03:00:00
